apiVersion: v1  
# Use core Kubernetes API (Services come under v1)

kind: Service  
# We are creating a Service (used to expose app)

metadata:
  name: devops-cicd-service  
  # Name of the Service (used to identify it)

spec:
  type: NodePort  
  # Exposes app outside cluster using a port on the node

  selector:
    app: devops-cicd-app  
    # Connects this Service to Pods with this label
    # Must match Deployment labels

  ports:
    - port: 80  
      # Service port (internal cluster communication)

      targetPort: 5000  
      # Port inside container (your app runs here)

      nodePort: 30007  
      # External port to access app from browser
      # Access using: http://<node-ip>:30007